### ISSUE TITLE
whitelist cookies from clearing on startup

### ISSUE THREAD

**Issue by jeroen7s** [Manvel/Privacy-Manager#30]
whitelisting certain cookies would prevent you from losing your current sessions on multiple websites, while still deleting the vast majority of cookies that have privacy implications
currently i'm using cookie autodelete for this, but i feel like this would be a nice addition to this

**Comment by Manvel** [comment]
@jeroen7s Thanks, I've added you to the Contributors list -> https://github.com/Manvel/Privacy-Manager/blob/master/README.md#thanks-to-the-awesome-contributors 

Hope you don't mind, thanks for the PR.

I'll try to followup on this later today and prepare linters and test build, so we can launch the new feature next week.

I don't have a proper release blog for Privacy Managers, but it's on the way as soon website will be ready on `privacymanagers.org` otherwise I would have added that into a proper release post.

Cheers!
